export const CONFIG = {
  MAX_RENT: 50000,
  MIN_RENT: 5000,
  MAX_BEDS: 4,
  MIN_BEDS: 1,
  MAX_PHOTOS: 3,
  MAX_PHOTO_SIZE_MB: 5,
  PHOTO_MAX_WIDTH: 800,
  LANDMARK_CHAR_MIN: 3,
  LANDMARK_CHAR_MAX: 100,
  COOLDOWN_SECONDS: 30,
}